Use global Faust (again)

diff --git a/.github/workflows/web.yml b/.github/workflows/web.yml
--- a/.github/workflows/web.yml
+++ b/.github/workflows/web.yml
@@ -17,9 +17,10 @@ jobs:
         toolchain: nightly
         override: true
         target: wasm32-unknown-emscripten
-    - uses: Swatinem/rust-cache@v1
-      with:
-        cache-on-failure: true
+    # FIXME(2021-10-03)
+    # uses: Swatinem/rust-cache@v1
+    # with:
+    #   cache-on-failure: true
     - uses: kofigumbs/setup-emsdk@master # FIXME(https://github.com/mymindstorm/setup-emsdk/pull/22)
       with:
         version: '2.0.29'
@@ -28,8 +29,19 @@ jobs:
     - run: |-
         npm install --global npm@7 netlify-cli@6
         npm install
+        # Install Faust to node_modules, so that it's cached by setup-node
+        [[ -x node_modules/.faust/faust && -d node_modules/.faust/libraries ]] || (
+          git clone --depth 1 https://github.com/grame-cncm/faust --branch $FAUST_VERSION $RUNNER_TEMP/faust
+          make -C $RUNNER_TEMP/faust compiler
+          mkdir -p node_modules/.faust
+          cp -r $RUNNER_TEMP/faust/{build/bin/faust,libraries} node_modules/.faust
+        )
+        echo $(pwd)/node_modules/.faust >> $GITHUB_PATH
+      env:
+        FAUST_VERSION: 2.33.1
     - env:
         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
         NODE_OPTIONS: '--max_old_space_size=6000' # FIXME(https://github.com/vitejs/vite/issues/4162)
+        FAUST_LIB_PATH: node_modules/.faust/libraries
       run: netlify deploy --build --prod
